/**
 * CodexBackend — spawns OpenAI `codex` (Codex CLI) in a pty.
 *
 * Mirrors ClaudeCodeBackend's approach. Hook plumbing is the same
 * (our hook-forwarder.js + Unix socket + per-session BATON_SESSION_ID
 * env). The differences:
 *
 *   - Codex has no `--settings <file>` flag. We instead write a
 *     per-session profile TOML at `$CODEX_HOME/baton-<sid>.config.toml`
 *     and spawn with `-p baton-<sid>`. The profile layers on top of
 *     the user's base `~/.codex/config.toml` — auth, model, providers
 *     all still apply.
 *   - The hook event taxonomy maps cleanly to Claude's: `SessionStart`,
 *     `UserPromptSubmit`, `PreToolUse`, `Notification`, `Stop`. The
 *     hook command takes the event name as $1 so the forwarder ships
 *     identical payload shapes either way.
 *   - YOLO equivalent is `--dangerously-bypass-approvals-and-sandbox`.
 *   - Codex enforces per-hook persisted trust hashes — would prompt
 *     on first run and block our forwarder. We always pass
 *     `--dangerously-bypass-hook-trust` since we're the ones writing
 *     the profile.
 *   - Codex has no `SessionEnd` hook; pty exit drives end-of-life
 *     via SessionManager.markExited just like Claude's path.
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import * as pty from 'node-pty';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type {
  AgentBackend,
  AgentHandle,
  AgentSpawnOpts,
} from './agentBackend.js';
import type { PermissionMode } from '../../shared/ipc.js';
import { getHookServer } from './hookServer.js';
import { trustDirectoryForCodex } from './codexTrust.js';

const execFileAsync = promisify(execFile);

export interface CodexSpawnOpts extends AgentSpawnOpts {
  sessionId: string;
  /** When set, spawn with `codex resume <id>` to reload a prior
   *  conversation. */
  resumeAgentSessionId?: string;
  /** Tool-permission posture. Codex has no intermediate modes, so only
   *  'bypassPermissions' is actionable here — it maps to
   *  `--dangerously-bypass-approvals-and-sandbox`. Every other value
   *  (including 'default') leaves Codex in its prompt-each-tool mode. */
  permissionMode?: PermissionMode;
}

const HOOK_EVENTS = [
  'SessionStart',
  'UserPromptSubmit',
  'PreToolUse',
  'Notification',
  'Stop',
] as const;

export class CodexBackend implements AgentBackend {
  readonly id = 'codex' as const;

  async isInstalled(): Promise<boolean> {
    try {
      const { stdout } = await execFileAsync('codex', ['--version']);
      return /\d+\.\d+/.test(stdout);
    } catch {
      return false;
    }
  }

  async spawn(opts: CodexSpawnOpts): Promise<AgentHandle> {
    // Pre-trust the cwd so Codex doesn't block our hooks on a "Trust
    // this workspace?" prompt. Same defensive pattern as Claude.
    trustDirectoryForCodex(opts.cwd);

    const hooks = getHookServer();
    const forwarder = hooks.forwarderPath();

    // Per-session profile. Codex resolves `-p NAME` to
    // `$CODEX_HOME/NAME.config.toml`, layered atop the base config.
    const codexHome = process.env['CODEX_HOME']
      ?? path.join(os.homedir(), '.codex');
    fs.mkdirSync(codexHome, { recursive: true });
    const profileName = `baton-${opts.sessionId}`;
    const profilePath = path.join(codexHome, `${profileName}.config.toml`);

    // The hook command is a shell command line. Single-quote the
    // forwarder path if it contains anything beyond the safe charset
    // so the shell doesn't word-split it. The full line then goes
    // into a TOML basic string with the usual escapes.
    const hookCmd = (event: string): string =>
      `node ${shellQuote(forwarder)} ${event}`;

    const tomlLines: string[] = [
      '# Generated by baton — per-session hook config. Auto-cleaned on pty exit.',
      '',
    ];
    for (const ev of HOOK_EVENTS) {
      tomlLines.push(`[[hooks.${ev}]]`);
      tomlLines.push(`matcher = "*"`);
      tomlLines.push('');
      tomlLines.push(`[[hooks.${ev}.hooks]]`);
      tomlLines.push(`type = "command"`);
      tomlLines.push(`command = ${tomlBasicString(hookCmd(ev))}`);
      tomlLines.push('');
    }
    fs.writeFileSync(profilePath, tomlLines.join('\n'));

    const env = {
      ...process.env,
      TERM: 'xterm-256color',
      COLORTERM: 'truecolor',
      BATON_HOOK_SOCK: hooks.sockPath(),
      BATON_SESSION_ID: opts.sessionId,
      ...(opts.env ?? {}),
    } as Record<string, string>;

    // Build args. Subcommand (resume) must come BEFORE options.
    const args: string[] = [];
    if (opts.resumeAgentSessionId) {
      args.push('resume', opts.resumeAgentSessionId);
    }
    args.push('--profile', profileName);
    // We wrote the profile ourselves — skip Codex's hook-trust prompt
    // so the agent doesn't block on first-run confirmation.
    args.push('--dangerously-bypass-hook-trust');
    if (opts.permissionMode === 'bypassPermissions') {
      args.push('--dangerously-bypass-approvals-and-sandbox');
    }
    // `--cd` is equivalent to pty.spawn's cwd, but Codex respects this
    // explicitly for its workspace bounds (sandbox / add-dir scope).
    args.push('--cd', opts.cwd);

    const ptyProcess = pty.spawn('codex', args, {
      name: 'xterm-256color',
      cols: opts.cols,
      rows: opts.rows,
      cwd: opts.cwd,
      env,
    });

    return wrap(ptyProcess, () => {
      try { fs.unlinkSync(profilePath); } catch { /* best-effort */ }
    });
  }
}

function wrap(ptyProcess: pty.IPty, onCleanup: () => void): AgentHandle {
  let alive = true;
  return {
    pid: ptyProcess.pid,
    write(data) {
      if (!alive) return;
      ptyProcess.write(data);
    },
    resize(cols, rows) {
      if (!alive) return;
      ptyProcess.resize(cols, rows);
    },
    kill(signal) {
      if (!alive) return;
      alive = false;
      try { ptyProcess.kill(signal ?? 'SIGTERM'); }
      catch { /* pty might already be gone */ }
      onCleanup();
    },
    pause() {
      if (!alive) return;
      try { ptyProcess.kill('SIGSTOP'); } catch { /* already gone */ }
    },
    resume() {
      if (!alive) return;
      try { ptyProcess.kill('SIGCONT'); } catch { /* already gone */ }
    },
    onData(handler) {
      const sub = ptyProcess.onData((s) => handler(Buffer.from(s, 'utf-8')));
      return () => sub.dispose();
    },
    onExit(handler) {
      const sub = ptyProcess.onExit((e) => {
        try { onCleanup(); } catch { /* ignore */ }
        handler(e.exitCode ?? null, e.signal ?? null);
      });
      return () => sub.dispose();
    },
  };
}

/** Wrap a TOML basic string (double-quoted) with backslash/quote
 *  escaping. */
function tomlBasicString(s: string): string {
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"') + '"';
}

/** POSIX-shell single-quote a string if it contains anything outside
 *  the safe charset. Otherwise return it unchanged so the generated
 *  config stays readable. */
function shellQuote(s: string): string {
  if (/^[\w./@:+,-]+$/.test(s)) return s;
  return `'${s.replace(/'/g, `'\\''`)}'`;
}
